# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

print(np.__version__)
np.show_config()


1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
raqamlar = [1, 2, 3, 4, 5]
massiv = np.array(raqamlar)

print(massiv)

[1 2 3 4 5]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [3]:
toqqiz_olchovli_massiv = np.zeros(9)

print(toqqiz_olchovli_massiv)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [4]:
massiv = np.array([1, 2, 3, 4, 5])

xotira_hajmi = massiv.itemsize

print(f"Massiv xotira hajmi: {xotira_hajmi} bayt")

Massiv xotira hajmi: 8 bayt


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [10]:
vektor = np.zeros(12)
vektor[5] = 1

print(vektor)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [11]:
vektor = np.arange(20, 60)

print(vektor)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [13]:
vektor = np.array([1, 2, 3, 4, 5])
teskari_vektor = vektor[::-1]

print(teskari_vektor)

[5 4 3 2 1]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [14]:
matritsa = np.arange(12, 21).reshape(3, 3)

print(matritsa)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [16]:
matritsa = np.array([3, 7, 0, 0, 9, 0])

indekslar = np.nonzero(matritsa)[0]

print("Nolga teng bo'lmagan elementlar indekslari:", indekslar)

Nolga teng bo'lmagan elementlar indekslari: [0 1 4]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [17]:
tasodifiy_massiv = np.random.random((2, 2, 2))

print(tasodifiy_massiv)

[[[0.82014117 0.97290475]
  [0.22958355 0.57357769]]

 [[0.27875553 0.15558411]
  [0.20351332 0.5110922 ]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [18]:
massiv = np.random.random((9, 9))

eng_katta_qiymat = np.max(massiv)
eng_kichik_qiymat = np.min(massiv)

print("Eng katta qiymat:", eng_katta_qiymat)
print("Eng kichik qiymat:", eng_kichik_qiymat)

Eng katta qiymat: 0.9970951637132422
Eng kichik qiymat: 0.0007426118501772105


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [19]:
print(0 * np.nan)          # NaN
print(np.nan == np.nan)     # False
print(np.inf > np.nan)      # False
print(np.nan - np.nan)      # NaN
print(np.nan in set([np.nan]))  # True
print(0.7 == 7 * 0.1)       # False

nan
False
False
nan
True
False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [21]:

matritsa1 = np.ones((6, 3))

matritsa2 = np.ones((3, 4))

kopaytma = np.dot(matritsa1, matritsa2)

print("Kopaytma:")
print(kopaytma)

Kopaytma:
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
9
10


10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [24]:
# Massivlar yaratish
a = np.array([1, 2])
b = np.array([4, 5])

# a > b
print("a > b")
print(a > b)

# a >= b
print("a >= b")
print(a >= b)

# a < b
print("a < b")
print(a < b)

# a <= b
print("a <= b")
print(a <= b)

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
print(np.array(0) / np.array(0))   # nan
print(np.array(0) // np.array(0))  # 0
print(np.array([np.nan]).astype(int).astype(float))  # [-2.14748365e+09]

nan
0
[-9.22337204e+18]


<ipython-input-25-ad191efe70b7>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))   # nan
<ipython-input-25-ad191efe70b7>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))  # 0


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [26]:
# Ikkita massiv yaratish
massiv1 = np.array([1, 2, 3, 4, 5])
massiv2 = np.array([3, 4, 5, 6, 7])

# Umumiy qiymatlarini topshirish
umumiy_qiymatlar = np.intersect1d(massiv1, massiv2)

print("Umumiy qiymatlar:", umumiy_qiymatlar)

Umumiy qiymatlar: [3 4 5]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [27]:
# Tasodifiy sonlardan iborat bo'lgan massiv yaratish
massiv = np.random.randn(5) * 10

# % operatori orqali musbat sonlarning butun qismini ajratib olish
ajratish1 = massiv % 1

# np.floor funktsiyasi orqali musbat sonlarning butun qismini ajratib olish
ajratish2 = np.floor(massiv)

# astype(int) metodi orqali massivni int tipiga o'zgartirib olish
ajratish3 = massiv.astype(int)

# np.trunc funktsiyasi orqali musbat sonlarning butun qismini ajratib olish
ajratish4 = np.trunc(massiv)

# Natijalarni chiqarish
print("Massiv:", massiv)
print("%% operatori natijasi:   ", ajratish1)
print("np.floor natijasi:       ", ajratish2)
print("astype(int) natijasi:    ", ajratish3)
print("np.trunc natijasi:       ", ajratish4)

Massiv: [ 6.79050302  6.46296485 -3.45755878 15.96354599 -4.54721417]
%% operatori natijasi:    [0.79050302 0.46296485 0.54244122 0.96354599 0.45278583]
np.floor natijasi:        [ 6.  6. -4. 15. -5.]
astype(int) natijasi:     [ 6  6 -3 15 -4]
np.trunc natijasi:        [ 6.  6. -3. 15. -4.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [28]:
matritsa = np.arange(9).reshape(3, 3)

print(matritsa)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [29]:
# Tasodifiy o'lchamlari 10 bo'lgan vektor yaratish
vektor = np.random.randint(1, 101, 10)

# O'sish tartibida chiqarish
vektor_osish = np.sort(vektor)

# Natijani chiqarish
print("Asl vektor:", vektor)
print("O'sish tartibida:", vektor_osish)

Asl vektor: [27  3 56 44 73  5 77 12 81 70]
O'sish tartibida: [ 3  5 12 27 44 56 70 73 77 81]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [30]:
# Ikki tasodifiy massivni yaratish
A = np.random.random((3, 3))
B = A.copy()  # A ning nusxasini olish

# Tenglikni tekshirish
tenglik1 = np.allclose(A, B)
tenglik2 = np.array_equal(A, B)

# Natijalarni chiqarish
print("A massivi:")
print(A)
print("\nB massivi:")
print(B)
print("\nTenglik np.allclose bilan:", tenglik1)
print("Tenglik np.array_equal bilan:", tenglik2)

A massivi:
[[0.80165655 0.48579555 0.87970164]
 [0.74377766 0.26461585 0.86242881]
 [0.20265874 0.5431603  0.71398272]]

B massivi:
[[0.80165655 0.48579555 0.87970164]
 [0.74377766 0.26461585 0.86242881]
 [0.20265874 0.5431603  0.71398272]]

Tenglik np.allclose bilan: True
Tenglik np.array_equal bilan: True


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [32]:
# 6x3 va 3x4 matritsalarni yaratish
matritsa1 = np.random.random((6, 3))
matritsa2 = np.random.random((3, 4))

# Ko'paytirish
kopaytma = np.dot(matritsa1, matritsa2)

# Natijani chiqarish
print("Matritsa 1:")
print(matritsa1)
print("\nMatritsa 2:")
print(matritsa2)
print("\nKo'paytma:")
print(kopaytma)

Matritsa 1:
[[0.23085448 0.39193725 0.00219017]
 [0.7836712  0.82799026 0.87218755]
 [0.45795263 0.08466824 0.1686243 ]
 [0.84970919 0.19373112 0.68304886]
 [0.01965306 0.97581431 0.78570939]
 [0.83706574 0.33740415 0.45845612]]

Matritsa 2:
[[0.69424472 0.47375428 0.82303594 0.55150493]
 [0.87925084 0.02790053 0.52303723 0.50689347]
 [0.29555625 0.87277017 0.77398598 0.22534198]]

Ko'paytma:
[[0.50552798 0.12221507 0.39669447 0.32648136]
 [1.5298512  1.15558823 1.75312022 1.04844186]
 [0.44221378 0.36648956 0.55170895 0.33347904]
 [0.96212373 1.00410323 1.32934003 0.72073943]
 [1.1038509  0.72228017 1.13469044 0.68252598]
 [1.01329093 0.80610405 1.22024872 0.73598326]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [33]:
# Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yaratish
vektor = np.random.random(5)

# Eng katta qiymatning indeksini topish
max_indeks = np.argmax(vektor)

# Eng katta qiymatni 0 ga o'zgartirish
vektor[max_indeks] = 0

# Natijani chiqarish
print("Asl vektor:", vektor)

Asl vektor: [0.1053397  0.         0.59149596 0.31368075 0.41882272]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [34]:
# Bugungi sana
bugun = np.datetime64('today', 'D')

# Kechagi sana
kecha = bugun - np.timedelta64(1, 'D')

# Ertangi sana
ertaga = bugun + np.timedelta64(1, 'D')

# Natijalarni chiqarish
print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

Kecha: 2023-11-08
Bugun: 2023-11-09
Ertaga: 2023-11-10


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [35]:
# 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni olish
sanalar = np.arange('2016-01', '2016-02', dtype='datetime64[D]')

# Natijalarni chiqarish
print(sanalar)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [37]:
# Tasodifiy sonlardan iborat bo'lgan massiv yaratish
tasodifiy_massiv = np.random.randn(10) * 10

# % operatori orqali musbat sonlarning butun qismini ajratib olish
ajratish1 = tasodifiy_massiv % 1

# np.floor funktsiyasi orqali musbat sonlarning butun qismini ajratib olish
ajratish2 = np.floor(tasodifiy_massiv)

# astype(int) metodi orqali massivni int tipiga o'zgartirib olish
ajratish3 = tasodifiy_massiv.astype(int)

# np.trunc funktsiyasi orqali musbat sonlarning butun qismini ajratib olish
ajratish4 = np.trunc(tasodifiy_massiv)

# Natijalarni chiqarish
print("Asl massiv:", tasodifiy_massiv)
print("%% operatori natijasi:   ", ajratish1)
print("np.floor natijasi:       ", ajratish2)
print("astype(int) natijasi:    ", ajratish3)
print("np.trunc natijasi:       ", ajratish4)

Asl massiv: [  1.15474854 -10.07433519  -3.96455959  12.45878165  -9.53413847
  -4.08926298  -6.34804924  -2.46345918   5.0588488   16.89433123]
%% operatori natijasi:    [0.15474854 0.92566481 0.03544041 0.45878165 0.46586153 0.91073702
 0.65195076 0.53654082 0.0588488  0.89433123]
np.floor natijasi:        [  1. -11.  -4.  12. -10.  -5.  -7.  -3.   5.  16.]
astype(int) natijasi:     [  1 -10  -3  12  -9  -4  -6  -2   5  16]
np.trunc natijasi:        [  1. -10.  -3.  12.  -9.  -4.  -6.  -2.   5.  16.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [38]:
# Ixtiyoriy kichik massivlar yaratish
massiv1 = np.random.random(100)
massiv2 = np.random.random(100)
massiv3 = np.random.random(100)

# Yig'indini hisoblash
yigindi = np.add.reduce([massiv1, massiv2, massiv3])

# Natijani chiqarish
print("Massiv 1:", massiv1)
print("Massiv 2:", massiv2)
print("Massiv 3:", massiv3)
print("\nYig'indisi:", yigindi)

Massiv 1: [0.16216439 0.78704604 0.56908635 0.626014   0.70884565 0.22493932
 0.06232215 0.38680512 0.54112537 0.69345949 0.41491462 0.54216591
 0.64664087 0.25138253 0.61032484 0.5943044  0.07749297 0.41089286
 0.00348346 0.52613956 0.90520605 0.52663246 0.26445205 0.23285497
 0.19504353 0.34903551 0.75834118 0.90348443 0.70770388 0.74437879
 0.06050638 0.89416692 0.12214697 0.55960883 0.09576352 0.41369298
 0.71873736 0.19769391 0.96492961 0.37561736 0.08029107 0.46938443
 0.64531254 0.89497822 0.94945227 0.97260599 0.84347707 0.21136256
 0.44133146 0.34687197 0.46905245 0.05715284 0.74412324 0.90135154
 0.00983092 0.01408141 0.88260475 0.02472353 0.01708274 0.37863822
 0.68121662 0.63857145 0.80438377 0.44815856 0.80087564 0.9412939
 0.05106878 0.73277036 0.02641108 0.1394857  0.04127057 0.36438105
 0.15304037 0.10951676 0.84390187 0.59020629 0.86523142 0.12286605
 0.92759312 0.22593463 0.72111355 0.83475932 0.74200713 0.63284411
 0.09950985 0.75067728 0.69322252 0.26182444 0.414898

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [40]:
# Berilgan vektor
vektor = np.array([1, 2, 3, 4, 5])

# Har bir qiymat orasiga ketma-ket 3 ta nol qo'shish
vektor_tuzilgan = np.zeros(len(vektor) * 3 + len(vektor) - 1)
vektor_tuzilgan[::4] = vektor

# Natijani chiqarish
print("Asl vektor:", vektor)
print("Tuzilgan vektor:", vektor_tuzilgan.astype(int))

Asl vektor: [1 2 3 4 5]
Tuzilgan vektor: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [41]:
# Berilgan a massivi
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# b massivini yaratish
b = np.lib.stride_tricks.as_strided(a, shape=(11, 4), strides=(a.itemsize, a.itemsize))

# Natijani chiqarish
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [46]:
# Ixtiyoriy sonlardan tashkil topgan massiv
massiv = np.random.randint(1, 11, size=20)

# Massivni ekranga chiqarish
print("Ixtiyoriy massiv:", massiv)

# Massivda o'xshash qiymatlarni topish
o_xshash_qiymatlar = np.unique(massiv)

# Qiymatlarni ekranga chiqarish
print("O'xshash qiymatlar:", o_xshash_qiymatlar)

# Massivda har bir o'xshash qiymat uchun nechta marta paydo bo'lganligini hisoblash
son_korsatkich = np.bincount(massiv)

# Eng ko'p paydo bo'lgan qiymatni topish
eng_kop_paydo_bolgan_qiymat = np.argmax(son_korsatkich)

# Natijani ekranga chiqarish
print(f"\nEng ko'p paydo bo'lgan qiymat: {eng_kop_paydo_bolgan_qiymat} ({son_korsatkich[eng_kop_paydo_bolgan_qiymat]} marta)")

Ixtiyoriy massiv: [8 1 7 6 6 5 1 8 5 5 4 4 5 2 7 2 7 7 1 7]
O'xshash qiymatlar: [1 2 4 5 6 7 8]

Eng ko'p paydo bo'lgan qiymat: 7 (5 marta)


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`