In [ ]:
import numpy as np

my_list = list(range(100000))  #python list 0~99999 ---> Normal
my_array = np.array(range(100000))  #numpy array(massiv) 0~99999 ---> Vektorlashgan




In [ ]:
%time for _ in range(10): [x*2 for x in my_list]  #Normal

CPU times: user 52 ms, sys: 643 µs, total: 52.6 ms
Wall time: 52.7 ms


In [ ]:
%time for _ in range(10): my_array*2  #Vektorlashgan usul

CPU times: user 2.07 ms, sys: 0 ns, total: 2.07 ms
Wall time: 5.37 ms


In [ ]:
import numpy as np

data1 = [3.5, 5, 6, 2] # list
arr1 = np.array(data1) # array1

In [ ]:
arr1

array([3.5, 5. , 6. , 2. ])

In [ ]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2)

In [ ]:
arr2

array([4. , 5. , 3.2, 7. ])

In [ ]:
arr1.ndim # array1 ning o'lchami

1

In [ ]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]] # list ichidagi list (nested list)
arr3 = np.array(data3) # array3

In [ ]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.ndim # array3 ning o'lchami

2

In [ ]:
data4 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] # list ichidagi list (nested list)
arr4 = np.array(data4) # array4

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr4.ndim # array4 ning o'lchami

3

In [ ]:
arr4.shape

(2, 2, 2)

In [ ]:
arr4.size # array3 ning elementlar soni

8

In [ ]:
arr5 = np.zeros((2, 4)) # barcha elemtlari 0 ga teng bo'lgan (2, 4)
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones((2, 4)) # barcha elementlari 1 ga teng bo'lgan (2, 4)
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr7 = np.arange(4, 20, 2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr8 = np.arange(20) # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr9 = np.random.rand(2, 4) # (2, 4) o'lchamli --> elementlar (0 ~ 1) taxminiy qiymatlardan tashkil topgan
arr9

array([[0.530078  , 0.91132059, 0.02143422, 0.08907723],
       [0.47629672, 0.80407283, 0.15695696, 0.29945127]])

In [ ]:
arr0 = np.random.randint(5, size=(2, 4)) # (2, 4) o'lchamli va max qiymati 5 gacha bo'lgan int sonlar
arr0

array([[1, 2, 2, 2],
       [2, 4, 4, 4]])

In [ ]:
arr11 = np.random.randn(2, 4) # (2, 4) o'lchamli --> elementlari (Normal dist)
arr11

array([[-0.93686822,  1.17337907,  1.31869966,  0.26785662],
       [ 1.92145542, -0.3321523 ,  1.31845614, -1.49073321]])

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64) # float64 malumot turiga ega massiv
arr1

array([1., 2., 3.])

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32)  # int32 malumot turiga ega massiv
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
arr1.dtype


dtype('float64')

In [ ]:
arr = np.array([1, 2, 3, 4]) # agar malumot turi korsatilmasa avtomatik tarzda int64 malumot turiga otkaziladi
arr

array([1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
float_arr= arr.astype(np.float64) # malumot turini ozgartirish
float_arr.dtype

dtype('float64')

In [ ]:
data = np.array([3.4, 4.5, 1.8, 5.2]) #float64
data.dtype

dtype('float64')

In [ ]:
int_data = data.astype(np.int64)
int_data

array([3, 4, 1, 5])

In [ ]:
import numpy as np


arr = np.arange(10, 100, 10)
arr
arr[1]
arr[3:5]


array([40, 50])

In [ ]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [ ]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [ ]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # (3, 3) o'lchamli massiv
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[1, 1]

5

In [ ]:
arr2d[2, 2]

9

In [ ]:
sl_arr2d = arr2d[2, 1:3]
sl_arr2d

array([8, 9])

In [ ]:
# 3D array
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3d[0][1, 1]

4

In [ ]:
arr3d[1][2, 1:]

array([16, 17])

In [ ]:
arr3d[2][0, :2]

array([18, 19])

In [ ]:
import numpy as np
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [ ]:
# data
data = np.random.randn(7, 4)
data

array([[-0.70847095, -0.56048628, -0.07522881,  0.28511281],
       [ 0.18391951, -0.15136787, -0.35678463, -1.539549  ],
       [-1.05510728,  0.4132979 , -0.06234877,  0.57449928],
       [ 0.39347733,  1.45619625, -1.61759584,  1.3774955 ],
       [-0.08098131,  0.83055768, -2.20616603,  1.20152583],
       [-0.53397025,  0.92523779,  0.01004404, -0.80481211],
       [ 0.02965454,  0.72741549, -1.17894722, -0.61832088]])

In [ ]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [ ]:
data[names == 'Hasan'] # Hasanga tegishli barcha ma'lumotlarni ajratib olish


array([[-0.70847095, -0.56048628, -0.07522881,  0.28511281],
       [-0.08098131,  0.83055768, -2.20616603,  1.20152583]])

In [ ]:
data[names == 'Husan'] # Husan tegishli barcha ma'lumotlarni ajratib olish

array([[ 0.18391951, -0.15136787, -0.35678463, -1.539549  ]])

In [ ]:
data[names=='Hasan', 2:] # Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish


array([[0.10046471, 0.80011866],
       [0.65338273, 0.71575702]])

In [ ]:
data[names == 'Husan', 1]

array([1.34915649])

In [ ]:
data[names != 'Hasan'] # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarni ajratib olish


array([[ 0.27574396,  1.34915649, -0.11820512,  0.86879903],
       [-1.0665883 ,  0.67688735, -1.32088483, -0.54127746],
       [ 0.01672354, -1.11523652,  0.13139442, -1.34879696],
       [ 1.30767987, -1.49213499, -0.70981938,  0.02795996],
       [ 1.32889512,  0.312497  ,  1.49640674,  1.17228933]])

In [ ]:
data[~(names == 'Hasan')] # (~) yuqoridagi cell bilan bir xil natijani berar ekan


array([[ 0.27574396,  1.34915649, -0.11820512,  0.86879903],
       [-1.0665883 ,  0.67688735, -1.32088483, -0.54127746],
       [ 0.01672354, -1.11523652,  0.13139442, -1.34879696],
       [ 1.30767987, -1.49213499, -0.70981938,  0.02795996],
       [ 1.32889512,  0.312497  ,  1.49640674,  1.17228933]])

In [ ]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 0.88453776 -1.35188696  0.10046471  0.80011866]
 [ 0.27574396  1.34915649 -0.11820512  0.86879903]
 [-1.0665883   0.67688735 -1.32088483 -0.54127746]
 [ 0.01672354 -1.11523652  0.13139442 -1.34879696]
 [ 0.19266541  1.15492138  0.65338273  0.71575702]
 [ 1.30767987 -1.49213499 -0.70981938  0.02795996]
 [ 1.32889512  0.312497    1.49640674  1.17228933]]


In [ ]:
mask = (names == 'Hasan') | (names == 'Husan') # "|" or (yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [ ]:
data[mask] # Hasan va Husanlarga tegishli ma'lumotlarni ajratib olish

array([[ 0.88453776, -1.35188696,  0.10046471,  0.80011866],
       [ 0.27574396,  1.34915649, -0.11820512,  0.86879903],
       [ 0.19266541,  1.15492138,  0.65338273,  0.71575702]])

In [ ]:
data

array([[ 0.88453776, -1.35188696,  0.10046471,  0.80011866],
       [ 0.27574396,  1.34915649, -0.11820512,  0.86879903],
       [-1.0665883 ,  0.67688735, -1.32088483, -0.54127746],
       [ 0.01672354, -1.11523652,  0.13139442, -1.34879696],
       [ 0.19266541,  1.15492138,  0.65338273,  0.71575702],
       [ 1.30767987, -1.49213499, -0.70981938,  0.02795996],
       [ 1.32889512,  0.312497  ,  1.49640674,  1.17228933]])

In [ ]:
data[data<0] = 0
data

array([[0.88453776, 0.        , 0.10046471, 0.80011866],
       [0.27574396, 1.34915649, 0.        , 0.86879903],
       [0.        , 0.67688735, 0.        , 0.        ],
       [0.01672354, 0.        , 0.13139442, 0.        ],
       [0.19266541, 1.15492138, 0.65338273, 0.71575702],
       [1.30767987, 0.        , 0.        , 0.02795996],
       [1.32889512, 0.312497  , 1.49640674, 1.17228933]])

In [ ]:
import numpy as np

def nd_array():
    """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi),
    qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
    arr = np.arange(0, 9, 1)
    arr = arr.reshape((3, 3))
    return arr

result = nd_array()
print(result)
result.ndim


[[0 1 2]
 [3 4 5]
 [6 7 8]]


2

In [ ]:
import numpy as np
def new():
    arr = np.arange(0, 15, 1)
    arr = arr.reshape((3, 5))
    return arr
new()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan
     qismini kesib olish funksiyasi """
    array = nd_array() # yuqoridagi funksiya yordamida array yaratib olish
    sliced = array[2, 0:2] # Ma'lumotlarni to'g'ri o'qish
    return sliced
sliced_array_2d()

array([6, 7])

In [ ]:
def sliced_array_3d():
    """3-o'lchamli massivni yuqoridagi listdan yaratish,
    hamda 12, 13, 15, va 16 elementlarini kesib olish funksiyasi"""
    arr3d = np.array([[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]])
    sliced = arr3d[1, 1:, :2]
    return sliced
sliced_array_3d()

array([[12, 13],
       [15, 16]])

In [ ]:
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    data = np.array(
        [[5, 6, 1, 1],
         [9, 1, 1, 1],
         [7, 7, 4, 2],
         [1, 5, 1, 9],
         [9, 9, 4, 5],
         [7, 5, 9, 6],
         [5, 3, 7, 4]]
    )
    mask = (names == 'Javohir') | (names == 'Elyor')
    return data[mask]
boolean_slicing()

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [ ]:
A = np.arange(0, 6).reshape(3, 2)  # A massiv : Elementlari 0~6 gacha, shape (3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.T  # A massiving Transpose korinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
A.swapaxes(1, 0) # A massiving Transpose korinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
np.dot(A, A.T) # AA^T hosil bo'lgan massiv bu A massivni A^T massivga ko'paytirb beradi

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

In [ ]:
import numpy as np
arr = np.arange(10) # 0 ~ 10 gacha bo'lgan elementlardan iborat massivni qaytaradi
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr) # arr nomli massivning barcha elementlaridan kv ildizni qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.square(arr) # arr nomli massivning barcha elementlarini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.exp(arr) # arr nomli massivning barcha elemntlarini eksponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(arr[1:]) # arr nomli massivning 0-elementdan tashqari barcha elementlarini logarifmini hisoblaydi (loge)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat taxminiy qiymatlarga ega massiv
arr1

array([-0.01344668,  0.72016237, -0.70171763, -1.11587273, -0.29150604,
       -2.13897388])

In [ ]:
qoldiq, butun = np.modf(arr1) # arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratadi

In [ ]:
print(qoldiq)
print(butun)

[-0.01344668  0.72016237 -0.70171763 -0.11587273 -0.29150604 -0.13897388]
[-0.  0. -0. -1. -0. -2.]


In [ ]:
np.sign(arr1) # arr1 massivining elementlari ishoralarini "-1" va "1" ko'rinishida qaytaradi

array([-1.,  1., -1., -1., -1., -1.])

In [ ]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [ ]:
arr1[0] = np.NaN # 0- elementimizni nan ga almashtirish

In [ ]:
arr1

array([        nan,  0.72016237, -0.70171763, -1.11587273, -0.29150604,
       -2.13897388])

In [ ]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

In [ ]:
# 2 ta massivni yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [ ]:
arr2

array([-1.97000386, -0.68751998, -1.98685469, -0.2410569 ,  2.06566931,
       -0.61072856])

In [ ]:
arr3

array([-0.25127813,  0.72990096, -0.50318072,  1.52877183, -0.2441951 ,
       -1.02579943])

In [ ]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi

array([-2.22128199,  0.04238098, -2.49003541,  1.28771493,  1.82147422,
       -1.63652799])

In [ ]:
arr2 + arr3 # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi

array([-2.22128199,  0.04238098, -2.49003541,  1.28771493,  1.82147422,
       -1.63652799])

In [ ]:
np.multiply(arr2, arr3) # arr2 va arr3 ning mos elementlarini ko'paytiradi

array([ 0.49501888, -0.50182149,  0.99974698, -0.36852101, -0.50442632,
        0.62648501])

In [ ]:
np.maximum(arr2, arr3) # arr2 va arr3 larning elementlarin taqqoslab, kattasining elementini qaytaradi

array([-0.25127813,  0.72990096, -0.50318072,  1.52877183,  2.06566931,
       -0.61072856])

In [ ]:
import numpy as np

# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [ ]:
# Shart
cond = np.array([True, False, True, True, False])

In [ ]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4, 4)  # (4, 4) taxminiy massiv
arr

array([[ 0.32807971, -0.39963587, -2.30315856,  0.82050859],
       [ 0.28736073, -1.26279443, -0.86350057,  0.47247801],
       [-1.69948304, -0.38405705,  1.29530429, -0.57530862],
       [-0.84491332,  0.29843687, -0.88708708, -1.32717222]])

In [ ]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[ 2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [-2, -2,  2, -2],
       [-2,  2, -2, -2]])

In [ ]:
# data
arr1 = np.arange(6).reshape(2, 3) # 0~6 gach bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) # 6 dan 11 gacha bo'lgan elementlardan tashkil topgan array

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# kvadratga oshirish (square)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
# kvadrat ildizdan (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [ ]:
import numpy as np
# data
arr = np.random.randn(5, 4) # (5, 4) o'lchovli massiv (random)
arr

array([[-0.96951665, -2.46409504, -1.31552369,  1.05714764],
       [-2.05735024,  0.6641165 , -2.07765578, -0.19921226],
       [-0.31451244,  1.74346521, -2.4589954 , -1.53713058],
       [-0.6784947 ,  1.02759521,  2.06433822,  1.72676002],
       [ 0.09112619,  0.24247616, -1.94192654,  0.58855875]])

In [ ]:
arr.sum() # arr ning barcha elementlarni yig'indisini hisoblab beradi

-6.808829419149004

In [ ]:
np.sum(arr) # arr ning barcha elementlarni yig'indisini hisoblab beradi

7.790669884168095

In [ ]:
arr.sum(axis=1) # qator yi'gindi

array([-3.69198774, -3.67010178, -2.56717321,  4.14019874, -1.01976543])

In [ ]:
arr.sum(axis=0) # ustun yi'gindi

array([ 4.23782506,  2.48519416,  2.51105697, -1.4434063 ])

In [ ]:
# sodda ma'lumot
data = np.arange(5) # 0 ~ 5 gacha bo'lgan elementlarda tashkil topgan massiv
data

array([0, 1, 2, 3, 4])

In [ ]:
mean = np.sum(data)/len(data)
mean

2.0

In [ ]:
# numpy mean
np.mean(data)

2.0

In [ ]:
data.mean()

2.0

In [ ]:
arr

array([[ 1.45724172,  0.07422493, -0.77940168, -0.42622919],
       [ 0.25665478,  0.26969466,  1.18595412, -0.73745251],
       [ 0.95049508,  0.58221124,  2.04731205,  1.64610855],
       [ 0.23084815,  1.73341374, -1.13218296, -0.40595147],
       [ 1.34258532, -0.17435042,  1.18937544, -1.51988168]])

In [ ]:
arr.mean()

0.3895334942084047

In [ ]:
np.mean(arr)  # arr ning ortacha qiymati

0.3895334942084047

In [ ]:
np.mean(arr, axis=1) # qator bo'yich o'rtach qiymatni qaytaradi

array([0.08145895, 0.24371276, 1.30653173, 0.10653187, 0.20943216])

In [ ]:
arr.mean(axis=0) # ustunlar bo'yicha o'rtacha qiymatni qaytaradi

array([ 0.84756501,  0.49703883,  0.50221139, -0.28868126])

In [ ]:
data

array([0, 1, 2, 3, 4])

In [ ]:
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [ ]:
import numpy as np
# data
arr = np.random.rand(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.9827997 , 0.58194889, 0.35048787, 0.09339298])

In [ ]:
# 1 usul
sorted_arr = np.sort(arr) # arr massivini tartiblangan ko'rinishini sorted_arr joylaydi
sorted_arr

array([0.09339298, 0.35048787, 0.58194889, 0.9827997 ])

In [ ]:
#  2 usul
arr.sort() # arr ning tartiblangan ko'rinishi
arr

array([0.09339298, 0.35048787, 0.58194889, 0.9827997 ])

In [ ]:
# teskari tartiblash
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.9827997 , 0.58194889, 0.35048787, 0.09339298])

In [ ]:
# 2 D array (massiv)
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[ 1.74289892, -0.53983063, -0.31405689,  0.16839909],
       [-1.18925545, -1.03583421,  0.64814389,  1.1986922 ]])

In [ ]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0) # arr2d ning xar bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[-1.18925545, -1.03583421, -0.31405689,  0.16839909],
       [ 1.74289892, -0.53983063,  0.64814389,  1.1986922 ]])

In [ ]:
# axis =1 --> Ustun
col_srt =np.sort(arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[-0.53983063, -0.31405689,  0.16839909,  1.74289892],
       [-1.18925545, -1.03583421,  0.64814389,  1.1986922 ]])

In [ ]:
import numpy as np
# data
names = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [ ]:
# unique
np.unique(names) # names dagi takrorlanmas elementlarni qaytaradi (takrorlansa ham faqat bittasini qabul qiladi)

array(['Abdurahmon', 'Hasan', 'Sarvar', 'Temur'], dtype='<U10')

In [ ]:
set(names) # names dagi unique(takrorlanmas) elementlarni qaytaradi

{'Abdurahmon', 'Hasan', 'Sarvar', 'Temur'}

In [ ]:
# data
arr1 = np.array([6, 0, 0, 3, 2, 5, 6])
arr2 = np.array([0, 2, 3])

In [ ]:
np.in1d(arr1, arr2) # arr2 dagi elementlarni arr1 da mavjudligini tekshirish

array([False,  True,  True,  True,  True, False, False])

In [ ]:
#data
names1 = np.array(['Jasur', 'Abdurahmon', 'Hasan',  'Muhammad', 'Sarvar', 'Temur'])
names2 = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])

In [ ]:
np.setdiff1d(names1, names2) # names1 massivining names2 massividagi takrorlanmas qismini qaytaradi

array(['Jasur', 'Muhammad'], dtype='<U10')

In [ ]:
import numpy as np

x= np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y = np.array([[6, 23], [-1, 7], [8, 9]])
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [ ]:
x.dot(y) # x*y

array([[ 28,  64],
       [ 67, 181]])

In [ ]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [ ]:
y.dot(x) # y*x

array([[ 98, 127, 156],
       [ 27,  33,  39],
       [ 44,  61,  78]])

In [ ]:
np.dot(y, x)

array([[ 98, 127, 156],
       [ 27,  33,  39],
       [ 44,  61,  78]])

In [1]:
# Linear Algebra
from numpy.linalg import inv

In [5]:
import numpy as np

ary = np.array([1, 2, 3, 5, 8])
ary = ary + 1
print(ary.ndim)

1


In [7]:
a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2)
c = a + b
print (c[4])

13


In [8]:
a = np.array([[1, 2], [3, 4]])
print(a.itemsize)

8


In [9]:
a = np.array([1, 2, 3, 5, 8])
b = np.array([0, 3, 4, 2, 1])
c = a+b
c = c*a
print(c[2])



21
